routes/web.php
<?php
/*
 * HRM - SAAS
 * Name:Ajay Kumar choudhary
 * Email:ajay@froiden.com
 */

# Employee Login
Route::group(["namespace" => 'Front', 'prefix' => 'panel'], function () {
    Route::get('/', ['as' => 'login', 'uses' => 'LoginController@index']);
    Route::post('/login', ['as' => 'login_check', 'uses' => 'LoginController@ajaxLogin']);
    Route::get('logout', ['as' => 'front.logout', 'uses' => 'LoginController@logout']);

    Route::post('password/reset', ['as' => 'front.password.post_reset', 'uses' => 'LoginController@post_reset']);
    Route::get('password/reset/{id}', ['as' => 'front.password.get_reset', 'uses' => 'LoginController@get_reset']);
    Route::post('forget_password', ['as' => 'front.forget_password', 'uses' => 'LoginController@forget_password']);

});
Route::group(["namespace" => 'Front'], function () {

    Route::post('password/reset', ['as' => 'front.password.post_reset', 'uses' => 'LoginController@post_reset']);
    Route::get('password/reset/{id}', ['as' => 'front.password.get_reset', 'uses' => 'LoginController@get_reset']);
    Route::post('forget_password', ['as' => 'front.forget_password', 'uses' => 'LoginController@forget_password']);

});

# Employee Panel After Login
Route::group(["namespace" => 'Front', 'middleware' => 'auth.employees', 'prefix' => 'panel'], function () {
    Route::post('/change_password_modal', ['as' => 'front.change_password_modal', 'uses' => 'DashboardController@changePasswordModal']);
    Route::post('/change_password', ['as' => 'front.change_password', 'uses' => 'DashboardController@change_password']);


    Route::get('salary_slip/{id}', ['as' => 'front.salary_slip', 'uses' => 'DashboardController@salary_show']);
    Route::get('downloadpdf/{id}', ['as' => 'front.payrolls.downloadpdf', 'uses' => 'DashboardController@downloadPdf']);
//    Route::get('leave', ['as' => 'front.leave', 'uses' => 'DashboardController@leave']);

    Route::get('salary', ['as' => 'front.salary', 'uses' => 'DashboardController@salary']);
    Route::get('employee/ajax_payroll', ['as' => 'front.ajax_payrolls', 'uses' => 'DashboardController@ajax_payrolls']);

    Route::get('dashboard/notice/{id}', ['as' => 'front.notice_ajax', 'uses' => 'DashboardController@notice_ajax']);

    Route::get('ajaxApplications/{id?}', ['as' => 'front.leave_applications', 'uses' => 'LeaveController@ajaxApplications']);
    Route::resource('leaves', 'LeaveController');

    Route::resource('jobs', 'JobFrontController');
    Route::resource('dashboard', 'DashboardController');

    Route::get('ajax_expenses/', ['as' => 'front.ajax_expenses', 'uses' => 'ExpenseFrontsController@ajax_expenses']);
    Route::resource('expenses', 'ExpenseFrontsController', ['as' => 'front']);

    Route::post('attendances/employee/ajax_load_calender', ['as' => 'front.attendance.ajax_load_calender', 'uses' => 'DashboardController@ajax_load_calender']);

    Route::get('front/attendance', ['uses' => 'AttendanceFrontController@index', 'as' => 'front.attendance.index']);
    Route::post('front/clock_in', ['uses' => 'AttendanceFrontController@clockIn', 'as' => 'front.attendance.clockIn']);
    Route::post('front/clock_out', ['uses' => 'AttendanceFrontController@clockOut', 'as' => 'front.attendance.clockOut']);
    Route::post('front/work_from', ['uses' => 'AttendanceFrontController@updateWorkFrom', 'as' => 'front.attendance.work_from']);
    Route::post('front/notes', ['uses' => 'AttendanceFrontController@updateNote', 'as' => 'front.attendance.notes']);
    Route::get('front/ajax_attendance', ['uses' => 'AttendanceFrontController@ajax_attendance', 'as' => 'front.attendance.ajax_attendance']);
});


# Admin Login
Route::group(["namespace" => 'Admin', "prefix" => "admin"], function () {

    Route::get('/', ['as' => 'admin.getlogin', 'uses' => 'AdminLoginController@index']);
    Route::get('logout', ['as' => 'admin.logout', 'uses' => 'AdminLoginController@logout']);

    Route::post('password/reset', ['as' => 'admin.password.post_reset', 'uses' => 'AdminLoginController@post_reset']);
    Route::get('verify_email/{id}', ['as' => 'admin.verify_email', 'uses' => 'AdminLoginController@verify_email']);
    Route::get('password/reset/{id}', ['as' => 'admin.password.get_reset', 'uses' => 'AdminLoginController@get_reset']);
    Route::post('forget_password', ['as' => 'admin.forget_password', 'uses' => 'AdminLoginController@forget_password']);
    Route::post('login', ['as' => 'admin.login', 'uses' => 'AdminLoginController@ajaxAdminLogin']);
    Route::post('register', ['as' => 'admin.register', 'uses' => 'AdminLoginController@register']);

});


// Admin Panel After Login
Route::group(["namespace" => 'Admin', 'middleware' => ['auth.admin', 'auth.screenlock', 'plan.null'], 'prefix' => 'admin'], function () {
    //	Dashboard Routing

    Route::post('updates/image_upload', ["as" => "admin.summernote.image_upload", "uses" => "AdminCommonController@image_upload"]);

    Route::post('attendances/ajax_load_calender', ['as' => 'admin.attendance.ajax_load_calender', 'uses' => 'AdminDashboardController@ajax_load_calender']);
    Route::get('resend_verify_email', ['as' => 'admin.dashboard.resend_verify_email', 'uses' => 'AdminDashboardController@resend_verify_email']);
    Route::resource('dashboard', 'AdminDashboardController', ['as' => 'admin']);

    //    Employees Routing
    Route::get('employees/ajax_employees/', ['as' => 'admin.ajax_employees', 'uses' => 'EmployeesController@ajax_employees']);
    Route::get('employees/export', ['as' => 'admin.employees.export', 'uses' => 'EmployeesController@export']);
    Route::get('employees/import', ['as' => 'admin.employees.import', 'uses' => 'EmployeesController@import']);
    Route::post('employees/import/upload', ['as' => 'admin.employees.importUpload', 'uses' => 'EmployeesController@importUpload']);
    Route::get('employees/import/match', ['as' => 'admin.employees.match', 'uses' => 'EmployeesController@match']);
    Route::post('employees/import/process', ['as' => 'admin.employees.importProcess', 'uses' => 'EmployeesController@importProcess']);
    Route::post('employees/import/checkStatus', ['as' => 'admin.employees.checkImportProgress', 'uses' => 'EmployeesController@checkImportProgress']);
    Route::post('employees/import/cancel', ['as' => 'admin.employees.cancelImport', 'uses' => 'EmployeesController@cancelImport']);
    Route::get('employees/import/failed_records', ['as' => 'admin.employees.failed_records', 'uses' => 'EmployeesController@failedRecords']);
    Route::get('employees/import/downloadFailedRecords', ['as' => 'admin.employees.downloadFailedRecords', 'uses' => 'EmployeesController@downloadFailedRecords']);
    Route::get('employees/employeeLogin/{id}', ['as' => 'admin.employees.employeeLogin', 'uses' => 'EmployeesController@employeesLogin']);
    Route::resource('employees', 'EmployeesController', ['except' => ['show'], 'as' => 'admin']);

    //  Awards Routing
    Route::get('ajax_awards/', ['as' => 'admin.ajax_awards', 'uses' => 'AwardsController@ajax_awards']);
    Route::resource('awards', 'AwardsController', ['except' => ['show'], 'as' => 'admin']);

    //  Department Routing
    Route::get('departments/ajax_designation/', ['as' => 'admin.departments.ajax_designation', 'uses' => 'DepartmentsController@ajax_designation']);
    Route::resource('departments', 'DepartmentsController', ['except' => ['show'], 'as' => 'admin']);

    //    Expense Routing
    Route::get('ajax_expenses/', ['as' => 'admin.ajax_expenses', 'uses' => 'ExpensesController@ajax_expenses']);
    Route::post('expense_change_status/{id}', ['as' => 'admin.expense.change_status', 'uses' => 'ExpensesController@change_status']);

    Route::resource('expenses', 'ExpensesController', ['except' => ['show'], 'as' => 'admin']);

    //    Holiday Routing
    Route::get('holidays/index/{year}', ['as' => 'admin.holidays.change_year', 'uses' => 'HolidaysController@index']);
    Route::get('holidays/mark_friday', 'HolidaysController@Friday');
    Route::get('holidays/mark_saturday', 'HolidaysController@Saturday');
    Route::get('holidays/mark_sunday', 'HolidaysController@Sunday');
    Route::get('holidays/un_mark', 'HolidaysController@removeAllWeekendHolidays');

    Route::resource('holidays', 'HolidaysController', ['as' => 'admin']);

    //  Routing for the attendance
    Route::get('attendances/ajax_employees/', ['as' => 'admin.attendance.ajax_employees', 'uses' => 'AttendancesController@ajax_employees']);
    Route::get('attendances/ajax_attendance', ['as' => 'admin.attendance.ajax_attendance', 'uses' => 'AttendancesController@ajax_attendance']);
    Route::get('attendances/report/{attendances}', ['as' => 'admin.attendance.report', 'uses' => 'AttendancesController@report']);
    Route::post('attendance/update/row', ['as' => 'admin.attendance.update.row', 'uses' => 'AttendancesController@updateAttendanceRow']);
    Route::post('attendance/clockIn', ['as' => 'admin.attendance.clockin', 'uses' => 'AttendancesController@clockInIP']);
    // attendance Filter route
    Route::post('attendances/filter', ['as'=>'admin.attendance.filter','uses'=>'AttendancesController@filterAttendance']);
    Route::get('attendances-employee', ['as'=>'admin.attendance.employee','uses'=>'AttendancesController@attendanceEmployee']);
    Route::resource('attendances', 'AttendancesController', ['as' => 'admin']);

    //   Routing or the leavetypes
    Route::get('leavetypes/ajax_list', ['as' => 'admin.leavetypes.ajax_list', 'uses' => 'LeavetypesController@ajaxLeaveType']);
    Route::resource('leavetypes', 'LeavetypesController', ['except' => ['show'], 'as' => 'admin']);

    //    Leave Applications routing
    Route::get('leave_applications/ajaxApplications', ['as' => 'admin.leave_applications', 'uses' => 'LeaveApplicationsController@ajaxApplications']);
    Route::resource('leave_applications', 'LeaveApplicationsController', ['except' => ['create', 'store', 'edit'], 'as' => 'admin']);

    //   Routing for setting

app/Models/Job.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

class Job extends BaseModel
{

    protected static function boot()
    {
        parent::boot();


        static::addGlobalScope('company', function (Builder $builder) {
            if (admin()) {
                $builder->where('jobs.company_id', admin()->company_id);
            }
            if (employee()) {
                $builder->where('jobs.company_id', employee()->company_id);
            }
        });


    }


    // Add your validation rules here
    public static $rules = ['position' => 'required', 'description' => 'required|min:20'];

    // Don't forget to fill this array
    protected $fillable = ['position', 'description', 'posted_date', 'last_date', 'close_date', 'status',
        'company_id'];

    public function setPostedDateAttribute($value)
    {
        $this->attributes['posted_date'] = date('Y-m-d', strtotime($value));
    }

    public function setLastDateAttribute($value)
    {
        $this->attributes['last_date'] = date('Y-m-d', strtotime($value));
    }

    public function setCloseDateAttribute($value)
    {
        $this->attributes['close_date'] = date('Y-m-d', strtotime($value));
    }

    public function scopeCompany($query, $id)
    {
        return $query->where('jobs.company_id', '=', $id);
    }
}

app/Http/Controllers/Admin/JobsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classes\Reply;
use App\Http\Controllers\AdminBaseController;

use App\Http\Requests\Admin\Job\DeleteRequest;
use App\Http\Requests\Admin\Job\EditRequest;
use App\Http\Requests\Admin\Job\StoreRequest;
use App\Http\Requests\Admin\Job\UpdateRequest;
use App\Models\Job;
use App\Models\Designation;
use App\Models\JobApplication;
use Illuminate\Support\Facades\View;

use Yajra\DataTables\Facades\DataTables;

class JobsController extends AdminBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = trans('pages.jobs.indexTitle');
        $this->jobsOpen = 'active';
        $this->jobsPostedActive = 'active';
        $this->designation = Designation::select('designation')->get()->toJson();
        $this->designation = str_replace('"designation"', "designation", $this->designation);
    }

    public function index()
    {
        return View::make('admin.jobs.index', $this->data);
    }

    // Datatable ajax request
    public function ajax_jobs()
    {
        $result = Job::select('id', 'position', 'posted_date', 'last_date', 'close_date', 'status', 'created_at')
            ->get();

        return DataTables::of($result)
            ->editColumn('status', function ($row) {
                $color = ['active' => 'success', 'inactive' => 'danger'];

                return "<span class='label label-{$color[$row->status]}'>" . trans("core." . $row->status) . "</span>";
            })->addColumn('edit', function ($row) {
                return '
                  <a  class="btn purple btn-sm margin-bottom-5"  onclick="loadView(\'' . route("admin.jobs.edit", $row->id) . '\')" ><i class="fa fa-edit"></i> ' . trans("core.btnViewEdit") . ' </a>
	              <a  href="javascript:;" onclick="del(\'' . $row->id . '\');return false;" class="btn red btn-sm margin-bottom-5">
                  <i class="fa fa-trash"></i> ' . trans("core.btnDelete") . ' </a>';
            })
            ->rawColumns(['status', 'edit'])
            ->make();
    }


    public function create()
    {
        $this->pageTitle = trans('pages.jobs.createTitle');
        return View::make('admin.jobs.create', $this->data);
    }


    public function store(StoreRequest $request)
    {


        Job::create($request->toArray());

        return Reply::redirect(route('admin.jobs.index'),'messages.addSuccess');
    }


    public function show($id)
    {
        $this->pageTitle = trans('pages.jobs.showTitle');
        //Check employee Company
        $check = Job::company($this->company_id)->find($id);

        if ($check == null) {
            return View::make('admin.errors.noaccess', $this->data);
        }

        $job = Job::findOrFail($id);

        return View::make('admin.jobs.show', compact('job'));
    }


    public function edit(EditRequest $request,$id)
    {
        $this->pageTitle = trans('pages.jobs.editTitle');

        $this->job = Job::find($id);

        return View::make('admin.jobs.edit', $this->data);
    }

    public function update(UpdateRequest $request, $id)
    {

        $job = Job::findOrFail($id);
        $job->update($request->toArray());
        return Reply::success('messages.updateSuccess');
    }


    public function destroy(DeleteRequest $request, $id)
    {

        Job::destroy($id);

        return Reply::success('messages.jobDeleteMessage');
    }

}

resources/views/admin/jobs/create.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')
    <!-- BEGIN PAGE LEVEL STYLES -->
    {!! HTML::style("assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css")!!}
    {!! HTML::style("assets/global/plugins/select2/css/select2.css")!!}
    {!! HTML::style("assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css") !!}
    {!! HTML::style("assets/global/plugins/jquery-multi-select/css/multi-select.css")!!}
    {!! HTML::style("assets/global/plugins/typeahead/typeahead.css")!!}
    {!! HTML::style("assets/global/plugins/bootstrap-summernote/summernote.css")!!}
    <!-- BEGIN THEME STYLES -->

@stop


@section('mainarea')


    <!-- BEGIN PAGE HEADER-->
    <div class="page-head">
        <div class="page-title"><h1>
                {{$pageTitle}}
            </h1></div>
    </div>
    <div class="page-bar">
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a onclick="loadView('{{route('admin.dashboard.index')}}')">{{__('core.home')}}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a onclick="loadView('{{ route('admin.jobs.index') }}')">@lang("pages.jobs.indexTitle")</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">{{__('core.btnAddJob')}}</span>
            </li>
        </ul>

    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->

            {{--INLCUDE ERROR MESSAGE BOX--}}

            {{--END ERROR MESSAGE BOX--}}


            <div class="portlet light bordered">


                <div class="portlet-body form">
                {!! Form::open(['class'=>'form-horizontal ajax_form','method'=>'POST']) !!}
                <!-- BEGIN FORM-->


                    <div class="form-body">

                        <div class="form-group">
                            <label class="col-md-2 control-label">{{trans('core.position')}} : <span
                                        class="required">
                                        * </span>
                            </label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="position" name="position"
                                       placeholder="{{trans('core.position')}} ">
                                <span class="help-block"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">{{trans('core.description')}} : <span
                                        class="required">
                                            * </span>
                            </label>

                            <div class="col-md-6">
										<textarea class="form-control" id="description"
                                                  name="description"></textarea>
                                <span class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">{{trans('core.postedDate')}} :
                            </label>

                            <div class="col-md-6">
                                <div class="input-group input-medium date date-picker"
                                     data-date-viewmode="years">
                                    <input type="text" class="form-control" name="posted_date" id="posted_date"
                                           data-date-viewmode="years" readonly
                                           value="{{date('d-m-Y')}}">
                                    <span class="input-group-btn">
                                                                   		<button class="btn default" type="button"><i
                                                                                    class="fa fa-calendar"></i></button>
                                                                   </span>
                                </div>

                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">{{trans('core.lastDateToApply')}}
                            </label>

                            <div class="col-md-6">
                                <div class="input-group input-medium date date-picker">
                                    <input type="text" class="form-control" name="last_date" id="last_date"
                                           data-date-format="dd-mm-yyyy" data-date-viewmode="years" readonly>
                                    <span class="input-group-btn">
                                                                   <button class="btn default" type="button"><i
                                                                               class="fa fa-calendar"></i></button>
                                                                   </span>
                                </div>

                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">{{trans('core.closeDate')}} :
                            </label>

                            <div class="col-md-6">
                                <div class="input-group input-medium date date-picker">
                                    <input type="text" class="form-control" name="close_date"
                                           data-date-format="dd-mm-yyyy" data-date-viewmode="years"
                                           id="close_date" readonly>
                                    <span class="input-group-btn">
																		 <button class="btn default" type="button"><i
                                                                                     class="fa fa-calendar"></i>
																		 </button>
																		 </span>
                                </div>
                            </div>
                        </div>


                        <!-- END FORM-->

                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-9">

                                <button type="button" id="jobCreate" class="btn green" onclick="ajaxCreateJob()">
                                    {{trans('core.btnSubmit')}}  </button>

                            </div>
                        </div>
                    </div>
                    {!!  Form::close()  !!}
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->

            </div>
        </div>
    </div>
    <!-- END PAGE CONTENT-->



@stop

@section('footerjs')

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    {!! HTML::script("assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js")!!}
    {!! HTML::script("assets/global/plugins/select2/js/select2.min.js")!!}
    {!! HTML::script("assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js")!!}
    {!! HTML::script("assets/global/plugins/bootstrap-summernote/summernote.min.js")!!}
    {!! HTML::script("assets/global/plugins/typeahead/typeahead.bundle.min.js")!!}
    {!! HTML::script("assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js") !!}
    {{--{!! HTML::script('assets/admin/pages/scripts/components-pickers.js')!!}--}}
    {!! HTML::script('assets/js/ajaxform/jquery.form.min.js')!!}
    <script>
        //	 ComponentsPickers.init();
        $('#description').summernote({height: 300});


        $('.date-picker').datepicker({dateFormat: 'dd-mm-yyyy'});

        var numbers = new Bloodhound({
            datumTokenizer: function (d) {
                return Bloodhound.tokenizers.whitespace(d.designation);
            },
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            local: {!! $designation!!}

        });

        // initialize the bloodhound suggestion engine
        numbers.initialize();

        // instantiate the typeahead UI
        if (App.isRTL()) {
            $('#typeahead_example_1').attr("dir", "rtl");
        }

        $('#typeahead_example_1').typeahead(null, {
            displayKey: 'designation',
            hint: (App.isRTL() ? false : true),
            source: numbers.ttAdapter()
        });

        function ajaxCreateJob() {
            $.easyAjax({
                url: "{!! route('admin.jobs.store') !!}",
                type: "POST",
                data: $(".ajax_form").serialize(),
                container: ".ajax_form",
            });
        }
    </script>
    <!-- END PAGE LEVEL PLUGINS -->
@stop

resources/views/admin/jobs/index.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')


    <!-- BEGIN PAGE LEVEL STYLES -->
    {!! HTML::style("assets/global/plugins/select2/css/select2.css")!!}
    {!! HTML::style("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css")!!}
    <!-- END PAGE LEVEL STYLES -->

@stop


@section('mainarea')


    <!-- BEGIN PAGE HEADER-->
    <div class="page-head">
        <div class="page-title"><h1>
                @lang("pages.jobs.indexTitle")
            </h1></div>
    </div>
    <div class="page-bar">
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a onclick="loadView('{{route('admin.dashboard.index')}}')">{{trans('core.dashboard')}}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">@lang("pages.jobs.indexTitle")</span>
            </li>

        </ul>

    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">


            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div id="load">

                {{--INLCUDE ERROR MESSAGE BOX--}}

                {{--END ERROR MESSAGE BOX--}}

            </div>
            <div class="portlet light bordered">

                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">

                                <a class="btn green" data-toggle="modal"
                                   onclick="loadView('{{URL::route('admin.jobs.create')}}')">
                                    {{__('core.btnAddJob')}}
                                    <i class="fa fa-plus"></i> </a>
                            </div>
                            <div class="col-md-6 form-group text-right">

                                <span id="load_notification"></span>
                                <input type="checkbox"
                                       onchange="ToggleEmailNotification('job_notification');return false;"
                                       class="make-switch" name="job_notification"
                                       @if($loggedAdmin->company->job_notification==1)checked @endif data-on-color="success"
                                       data-on-text="{{trans('core.btnYes')}}" data-off-text="{{trans('core.btnNo')}}"
                                       data-off-color="danger">
                                <strong>{{trans('core.emailNotification')}}</strong><br>
                            </div>
                        </div>
                    </div>


                    <table class="table table-striped table-bordered table-hover" id="jobs">
                        <thead>
                        <tr>
                            <th> @lang("core.serialNo") </th>
                            <th> {{trans('core.position')}} </th>

                            <th> {{trans('core.postedDate')}}  </th>
                            <th> {{trans('core.lastDateToApply')}}  </th>
                            <th> {{trans('core.closeDate')}}  </th>
                            <th> {{trans('core.status')}}  </th>
                            <th> {{trans('core.action')}}  </th>
                        </tr>
                        </thead>
                        <tbody>


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->

        </div>
    </div>
    <!-- END PAGE CONTENT-->

    {{--MODAL CALLING--}}
    @include('admin.common.delete')
    {{--MODAL CALLING END--}}
@stop



@section('footerjs')


    <!-- BEGIN PAGE LEVEL PLUGINS -->
    {!!  HTML::script("assets/global/plugins/select2/js/select2.min.js")!!}
    {!! HTML::script("assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js")!!}
    {!!  HTML::script("assets/global/plugins/datatables/datatables.min.js")!!}
    {!!  HTML::script("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")!!}

    <!-- END PAGE LEVEL PLUGINS -->

    <script>


        var table = $('#jobs').dataTable({
            processing: true,
            serverSide: true,
            {!! $datatabble_lang !!}
            "ajax": "{{ URL::route("admin.ajax_jobs") }}",
            "aaSorting": [[6, "desc"]],
            columns: [
                {data: 'id', name: 'id'},
                {data: 'position', name: 'position'},
                {data: 'posted_date', name: 'posted_date'},
                {data: 'last_date', name: 'last_date'},
                {data: 'close_date', name: 'close_date'},
                {data: 'status', name: 'status'},
                {data: 'edit', name: 'edit'},
            ],
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            "sPaginationType": "full_numbers",
            "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                var oSettings = this.fnSettings();
                $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                return nRow;
            }

        });

        // Show Delete Modal
        function del(id,) {

            $('#deleteModal').modal('show');

            $("#deleteModal").find('#info').html('@lang("messages.jobDeleteConfirm")');

            $('#deleteModal').find("#delete").off().click(function () {

                var url = "{{ route('admin.jobs.destroy',':id') }}";
                url = url.replace(':id', id);

                var token = "{{ csrf_token() }}";

                $.easyAjax({
                    type: 'DELETE',
                    url: url,
                    data: {'_token': token},
                    container: "#deleteModal",
                    success: function (response) {
                        if (response.status === "success") {
                            $('#deleteModal').modal('hide');
                            table.fnDraw();
                        }
                    }
                });

            });
        }
    </script>
@stop

resources/views/admin/jobs/show.blade.php
/Users/Ajay/htdocs/hrm/dev/local/app/views/jobs/show.blade.php