routes/web.php
    Route::get('billing/payment/cancel', ['as' => 'admin.billing.payment.cancel', 'uses' => 'BillingController@paymentCancel']);
    Route::get('billing/change-plan', ['as' => 'admin.billing.change_plan', 'uses' => 'BillingController@changePlan']);
    Route::get('paypal-recurring', array('as' => 'admin.paypal-recurring','uses' => 'AdminPaypalController@payWithPaypalRecurrring',));
    Route::get('billing/select-package/{packageID}',  'BillingController@selectPackage')->name('admin.billing.select-package');
    Route::post('billing/stripe-payment', ['as' => 'admin.billing.stripe_payment', 'uses' => 'BillingController@stripePayment']);
    Route::post('billing/unsubscribe', ['as' => 'admin.billing.unsubscribe', 'uses' => 'BillingController@cancelSubscription']);

    Route::get('paypal/{packageId}/{type}', array('as' => 'admin.paypal','uses' => 'AdminPaypalController@paymentWithpaypal'));
    Route::resource('billing', 'BillingController', ['as' => 'admin']);


});

// Superadmin Panel Routes
Route::group(["namespace" => 'Admin', 'middleware' => ['auth.superadmin', 'auth.screenlock'], 'prefix' => 'super-admin'], function () {

    Route::get('update-new-version', ['as' => 'admin.updateVersion.index', 'uses' => 'SuperAdminUpdateVersionController@index']);

    //   Profile Setting
    Route::get('profile-settings', ['as' => 'superadmin.profile_settings.edit', 'uses' => 'ProfileSettingsController@edit']);
    Route::post('profile-settings', ['as' => 'superadmin.profile_settings.update', 'uses' => 'ProfileSettingsController@update']);


    Route::get('earning/report/{year}', ['as' => 'admin.earning.report', 'uses' => 'SuperAdminDashboardController@createEarningReport']);
    Route::resource('dashboard', 'SuperAdminDashboardController', ['as' => 'superadmin']);

    //	Contact Request
    Route::post('contact_requests_change_status/', ['as' => 'admin.contact_requests.change_status', 'uses' => 'ContactRequestController@change_status']);
    Route::get('ajax_contact_requests/', ['as' => 'admin.ajax_contact_requests', 'uses' => 'ContactRequestController@ajax_contact_requests']);
    Route::resource('contact_requests', 'ContactRequestController', ['as' => 'admin']);

    //Email Templates
    Route::get('ajax_email_templates/', ['as' => 'admin.ajax_email_templates', 'uses' => 'EmailTemplatesController@ajax_email_templates']);
    Route::resource('email_templates', 'EmailTemplatesController', ['as' => 'admin']);


    // License Types
    Route::put('license_types_country_update/{id}', ['as' => 'admin.license_types_country.update', 'uses' => 'LicenseTypesController@update_country']);
    Route::get('license_types_country_edit/{id}', ['as' => 'admin.license_types_country.edit', 'uses' => 'LicenseTypesController@edit_country']);
    Route::get('ajax_license_types_country/', ['as' => 'admin.ajax_license_types_country', 'uses' => 'LicenseTypesController@ajax_license_types_country']);
    Route::get('ajax_license_types/', ['as' => 'admin.ajax_license_types', 'uses' => 'LicenseTypesController@ajax_license_types']);
    Route::resource('license_types', 'LicenseTypesController', ['as' => 'admin']);

    Route::get('ajax_plans/', ['as' => 'admin.plans', 'uses' => 'PlansController@ajax_plans']);
    Route::resource('plans', 'PlansController', ['as' => 'admin']);

    // FAQ Category
    Route::get('ajax_faq_categories/', ['as' => 'admin.faq_categories', 'uses' => 'FaqCategoryController@ajaxFaqCategories']);
    Route::resource('faq_categories', 'FaqCategoryController', ['as' => 'admin']);

    // FAQ
    Route::get('ajax_faq/', ['as' => 'admin.faqs', 'uses' => 'FaqController@ajaxFaqs']);
    Route::resource('faq', 'FaqController', ['as' => 'admin']);

    // Features
    Route::get('ajax_features/', ['as' => 'admin.features', 'uses' => 'FeaturesController@ajaxFeatures']);
    Route::resource('features', 'FeaturesController', ['as' => 'admin']);

    //Licenses
    Route::get('ajax_licenses/', ['as' => 'admin.ajax_licenses', 'uses' => 'LicenseController@ajax_licenses']);
    Route::resource('licenses', 'LicenseController', ['as' => 'admin']);

    // Trasactions
    Route::get('ajax_transactions/', ['as' => 'admin.ajax_transactions', 'uses' => 'TransactionsController@ajax_transactions']);
    Route::resource('transactions', 'TransactionsController', ['as' => 'admin']);

    Route::get('view_file/{type}/{filename}', ['as' => 'admin.view_file', 'uses' => 'AdminCommonController@view_file']);

    Route::get("support", ["as" => "admin.support", "uses" => "AdminDashboardController@support"]);

    //Referral Members
    Route::get('referral_members/ajax_members', ['uses' => 'ReferralMemberController@ajax_members', 'as' => 'admin.referral_members.ajax_members']);
    Route::post('referral_members/change_status', ['uses' => 'ReferralMemberController@change_status', 'as' => 'admin.referral_members.change_status']);
    Route::resource('referral_members', 'ReferralMemberController', ['as' => 'admin']);

    // Trasactions
    Route::get('download_backup/{id}', ['as' => 'admin.download_backup', 'uses' => 'DatabaseBackupAdminController@download_backup']);
    Route::get('ajax_database_backups/', ['as' => 'admin.ajax_database_backups', 'uses' => 'DatabaseBackupAdminController@ajax_database_backups']);
    Route::resource('database_backups', 'DatabaseBackupAdminController', ['as' => 'admin']);

    // Updates
    Route::resource('updates', 'AdminUpdatesController', ['as' => 'admin']);


    //region stripe settings superadmin
    Route::get('stripe_settings', ['as' => 'admin.stripe_settings', 'uses' => 'SettingsController@getStripe']);
    Route::post('stripe_settings', ['as' => 'admin.stripe_settings.update', 'uses' => 'SettingsController@postStripe']);
    //endregion

    // region superadmin invoices
    Route::get('invoices/ajax_invoices', ['uses' => 'SuperAdminInvoiceController@ajax_invoices'])->name('admin.ajax_invoices');
    Route::resource('invoices', 'SuperAdminInvoiceController', ['as' => 'admin'], ['only' => ['index']]);
    //endregion

    //  Company
    Route::get('company_theme/', ['as' => 'admin.companies.theme', 'uses' => 'CompaniesController@theme']);
    Route::get('ajax_company/', ['as' => 'admin.ajax_admin_company', 'uses' => 'CompaniesController@ajax_company']);
    Route::get('change_company/', ['as' => 'admin.change_company', 'uses' => 'CompaniesController@change_company']);

    Route::post('change_status/', ['as' => 'admin.companies.change_status', 'uses' => 'CompaniesController@change_status']);
    Route::get('companies/editPackage/{companyId}', ['uses' => 'CompaniesController@editPackage'])->name('admin.companies.edit-package.get');
    Route::put('companies/editPackage/{companyId}', ['uses' => 'CompaniesController@updatePackage'])->name('admin.companies.edit-package.post');
    Route::resource('companies', 'CompaniesController', ['as' => 'admin']);
    Route::get("companies/browse_history/{id}", ["as" => "admin.companies.browse_history", "uses" => "CompaniesController@browse_history"]);
    Route::get("companies/ajax_browse_history/{id}", ["as" => "admin.companies.ajax_browse_history", "uses" => "CompaniesController@ajax_browse_history"]);

    //region stripe settings superadmin
    Route::get('smtp_settings', ['as' => 'admin.smtp_settings', 'uses' => 'SettingsController@getSmtp']);
    Route::post('smtp_settings/sent-test-email', ['uses' => 'SettingsController@sendTestEmail'])->name('admin.smtp_settings.send-test-email');
    Route::post('email-settings/updateMailConfig', ['uses' => 'SettingsController@updateMailConfig'])->name('admin.email-settings.updateMailConfig');

    Route::put('update-gdpr', ['as' => 'admin.settings.update-gdpr', 'uses' => 'SettingsController@updateGDPR']);
    Route::get('gdpr', ['as' => 'admin.settings.gdpr', 'uses' => 'SettingsController@getGdpr']);

    //   Routing for setting
    Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update'], 'as' => 'admin']);


    //Admin Users
    Route::get('ajax_superadmin_users/', ['as' => 'admin.ajax_superadmin_users', 'uses' => 'SuperAdminUsersController@ajax_superadmin_users']);
    Route::resource('superadmin_users', 'SuperAdminUsersController', ['as' => 'admin']);
});


Route::post('verify-ipn', array('as' => 'verify-ipn','uses' => 'PaypalIPNController@verifyIPN'));
Route::post('verify-billing-ipn', array('as' => 'verify-billing-ipn','uses' => 'PaypalIPNController@verifyBillingIPN'));

// Stripe Webhook
Route::post('verify-stripe-webhook', ['as' => 'admin.stripe.verify_webhook', 'uses' => 'StripeWebhookController@verifyStripeWebhook']);
// Save invoices locally
Route::post('/save-invoices',['as' => 'admin.stripe.save_webhook', 'uses' => 'StripeWebhookController@saveInvoices']);

// Lock Screen Routing
Route::get('screenlock', ['middleware' => 'auth.admin', 'as' => 'admin.screen.lock', 'uses' => 'Admin\AdminDashboardController@screenlock']);
Route::post('screenlock/modal', ['middleware' => 'auth.admin', 'as' => 'admin.screenlock.modal', 'uses' => 'Admin\AdminDashboardController@screenlockModal']);

// Site Route
Route::get('/', ["as" => "home", "uses" => "Site\HomeController@index"]);
Route::get('features', ["as" => "features", "uses" => "Site\HomeController@features"]);
Route::get('plans', ["as" => "pricing", "uses" => "Site\HomeController@pricing"]);
Route::get('support', ["as" => "support", "uses" => "Site\HomeController@support"]);
Route::any('signup', ["as" => "signup", "uses" => "Site\HomeController@signup"]);
Route::any('terms-of-service', ["as" => "termsOfService", "uses" => "Site\HomeController@termsOfService"]);
Route::any('privacy-policy', ["as" => "privacyPolicy", "uses" => "Site\HomeController@privacyPolicy"]);
Route::any('system-requirements', ["as" => "systemRequirements", "uses" => "Site\HomeController@systemRequirements"]);
Route::post('signup/submit', ["as" => "signup.submit", "uses" => "Site\HomeController@submitSignup"]);

app/Models/ReferralMember.php
<?php

namespace App\Models;


class ReferralMember extends BaseModel
{


    protected $guarded = ['id'];
    protected $table = "referral_member";

    public static $rules_add = [
        'email' => 'required|unique:referral_member,email',
        "password" => 'required',
        'name' => 'required',
        'agreement' => 'mimes:pdf,doc,docx,png,jpg,jpeg|max:4000',
    ];

    public static $rules_edit = [
        'email' => 'required|unique:referral_member,email,:id,id',
        "referral_code" => 'required|unique:referral_member,referral_code,:id,id',
        'name' => 'required',
        'agreement' => 'mimes:pdf,doc,docx,png,jpg,jpeg|max:4000',
    ];

    public static function rules($id = false, $merge = [])
    {
        $rules = self::$rules_edit;
        if ($id) {
            foreach ($rules as &$rule) {
                $rule = str_replace(':id', $id, $rule);
            }
        }

        return array_merge($rules, $merge);
    }
}

resources/views/admin/referralmember/index.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')

<!-- BEGIN PAGE LEVEL STYLES -->
{!! HTML::style("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css")!!}
<!-- END PAGE LEVEL STYLES -->

@stop

@section('mainarea')


    <!-- BEGIN PAGE HEADER-->
    <div class="page-head"><div class="page-title"><h1>
        {{$pageTitle}}
    </h1></div></div>
    <div class="page-bar">
        <ul class="page-breadcrumb breadcrumb">
            <li>
                                          <a onclick="loadView('{{ route('admin.dashboard.index') }}')">{{ trans('core.home') }}</a>
                     <i class="fa fa-circle"></i>
                 </li>
            <li>
                <a href="#"> {{$pageTitle}}</a>

            </li>

        </ul>

    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->

    <div class="row">
        <div class="col-md-12">


            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div id="load">

                {{--INLCUDE ERROR MESSAGE BOX--}}

                {{--END ERROR MESSAGE BOX--}}

            </div>
            <div class="portlet light bordered">
                <div class="portlet-title">

                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">

                                <a class="btn green" data-toggle="modal" href="{{URL::route('admin.referral_members.create')}}">
                                        {{__('core.addReferral')}}
                                    <i class="fa fa-plus"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="portlet-body">


                    <table class="table table-striped table-bordered table-hover" id="referrals">
                        <thead>
                        <tr>
                            <th> Id. </th>
                            <th> Referral Code </th>
                            <th> Email </th>
                            <th> Name </th>
                            <th> Company Name </th>
                            <th> Position </th>
                            <th> Date of Agreement </th>
                            <th> Created at </th>
                            <th>Status</th>
                            <th class="text-center"> {{trans('core.action')}} </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($referralDef as $row)
                            <tr >
                                <td>{{$row->id}}</td>
                                <td>{{$row->referral_code}}</td>
                                <td>{{$row->email}}</td>
                                <td>{{$row->name}}</td>
                                <td>{{$row->company_name}}</td>
                                <td>{{$row->position}}</td>
                                <td>{{date('d-M-Y', strtotime($row->date_of_agreement))}}</td>
                                <td>{{date('d-M-Y', strtotime($row->created_at))}}</td>
                                <td>
                                    @php($color = ['active' => 'success', 'inactive' => 'danger'])
                                    <span id='status{{$row->id}}' class='label label-{{$color[$row->status]}}' >{{trans("core." . $row->status)}}</span>
                                </td>
                                <td>
                                    @if($row->status == 'active')
                                        @php($r_status = 'Disable')
                                        @php($color = 'blue-ebonyclay')
                                        @php($icon = 'ban')
                                    @else
                                        @php($r_status = 'Enable')
                                        @php($color = 'green')
                                        @php($icon = 'check')
                                    @endif
                                        <a  class="btn purple btn-sm margin-bottom-5"  href="{{route('admin.referral_members.edit', $row->id)}}" >
                                                        <i class="fa fa-edit"></i> {{trans("core.btnViewEdit") }}
                                                      </a>
                                                      <a  style="width: 94px" href="javascript:;" onclick="del('{{$row->id}}',' {{$row->referral_code}}');return false;" class="btn red btn-sm margin-bottom-10">
                                                                <i class="fa fa-trash"></i> {{ trans("core.btnDelete")}}</a>
                                                        <a  href="javascript:;" onclick="changeStatus({{$row->id}});return false;" class="btn {{$color}} btn-sm margin-bottom-10">
                                                                 <i class="fa fa-{{$icon}}"></i> {{$r_status}}</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->

        </div>
    </div>
    <!-- END PAGE CONTENT-->

    {{--MODAL CALLING--}}
        @include('admin.common.delete')
    {{--MODAL CALLING END--}}
@stop

@section('footerjs')
<!-- BEGIN PAGE LEVEL PLUGINS -->
    {!! HTML::script("assets/global/plugins/datatables/datatables.min.js")!!}
    {!! HTML::script("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")!!}
<script>

  var table =   $('#referrals').dataTable( {
        processing: true,
        serverSide: true,
        {!! $datatabble_lang !!}
        "ajax": "{{ URL::route("admin.referral_members.ajax_members") }}",
        "aaSorting": [[ 1, "asc" ]],
        "deferLoading":{{$total}},
        columns: [
            { data: 'id', name: 'id' },
            { data: 'referral_code', name: 'referral_code' },
            { data: 'email', name: 'email' },
            { data: 'name', name: 'name' },
            { data: 'company_name', name: 'company_name' },
            { data: 'position', name: 'position' },
            { data: 'date_of_agreement', name: 'date_of_agreement' },
            { data: 'created_at', name: 'created_at' },
            { data: 'status', name: 'status' },
            { data: 'edit', name: 'edit', "bSortable": false  }
        ],
        "lengthMenu": [
            [5, 15, 20, -1],
            [5, 15, 20, "All"] // change per page values here
        ],
        "sPaginationType": "full_numbers",

    });

  function del(id, code) {

    $('#deleteModal').modal('show');

    var msg = prepareMessage("@lang("messages.referralDeleteConfirm")", ":code", code);

    $("#deleteModal").find('#info').html(msg);
    $('#deleteModal').find("#delete").off().click(function () {
        var url = "{{ route('admin.referral_members.destroy',':id') }}";
        url = url.replace(':id', id);
        $.ajax({

            type: "DELETE",
            url: url,
            dataType: 'json',
            data: {"id": id}

        }).done(function (response) {

            if (response.success == "deleted") {
                $('#deleteModal').modal('hide');
                $('#row' + id).fadeOut(500);
                table._fnDraw();
                showToastrMessage(prepareMessage("@lang("messages.referralDeleteMessage")", ":code", code), '{{__('core.success')}}', 'success');

            }
        });
    })

}
function changeStatus(id){

    var url = "{{ route('admin.referral_members.change_status') }}";
    $.ajax({

        type: "POST",
        url: url,
        dataType: 'json',
        data: {"id": id}

    }).done(function (response) {
        table._fnDraw();
        showResponseMessage(response, "error");
    });
}
@if(Session::has('toastrHeading') && Session::has('toastrMessage'))
showToastrMessage("{{ Session::get('toastrMessage') }}", "{{ Session::get('toastrHeading') }}");
@endif
</script>
@stop