routes/web.php
    Route::get('leave_applications/ajaxApplications', ['as' => 'admin.leave_applications', 'uses' => 'LeaveApplicationsController@ajaxApplications']);
    Route::resource('leave_applications', 'LeaveApplicationsController', ['except' => ['create', 'store', 'edit'], 'as' => 'admin']);

    //   Routing for setting
    Route::get('change_language/', ['as' => 'admin.change_language', 'uses' => 'SettingsController@change_language']);
    Route::get('theme/', ['as' => 'admin.settings.theme', 'uses' => 'SettingsController@theme']);
    Route::resource('settings', 'SettingsController', ['only' => ['edit', 'update'], 'as' => 'admin']);

    //region stripe settings superadmin
    Route::get('stripe_settings', ['as' => 'admin.stripe_settings', 'uses' => 'SettingsController@getStripe']);
    //endregion


    //endregion

    //    Salary Routing
    Route::get('add-salary-modal/{employeeID}', ['as' => 'admin.add-salary-modal', 'uses' => 'SalaryController@addSalaryModal']);
    Route::resource('salary', 'SalaryController', ['only' => ['destroy', 'update', 'store'], 'as' => 'admin']);

    //   Profile Setting
    Route::get('profile-settings', ['as' => 'admin.profile_settings.edit', 'uses' => 'ProfileSettingsController@edit']);
    Route::post('profile-settings', ['as' => 'admin.profile_settings.update', 'uses' => 'ProfileSettingsController@update']);

    //   Notification Setting
    Route::post('ajax_update_notification', ['as' => 'admin.ajax_update_notification', 'uses' => 'CompanySettingsController@updateAjaxNotification']);
    Route::post('notification-settings', ['as' => 'admin.notification.update', 'uses' => 'CompanySettingsController@updateNotification']);

    Route::get('notification-settings', ['as' => 'admin.notification.edit', 'uses' => 'CompanySettingsController@notificationSetting']);


    //  Notice Board
    Route::get('ajax_notices/', ['as' => 'admin.ajax_notices', 'uses' => 'NoticeboardsController@ajax_notices']);
    Route::resource('noticeboards', 'NoticeboardsController', ['except' => ['show'], 'as' => 'admin']);

    // Payroll
    Route::get('payrolls/downloadpdf/{id}', ['as' => 'admin.payrolls.downloadpdf', 'uses' => 'PayrollsController@downloadPdf']);
    Route::post('payrolls/check/', ['as' => 'admin.payrolls.check', 'uses' => 'PayrollsController@check']);
    Route::get('ajax_payrolls/', ['as' => 'admin.ajax_payrolls', 'uses' => 'PayrollsController@ajax_payrolls']);
    Route::post('payroll_report/', ['as' => 'admin.payroll_report', 'uses' => 'PayrollsController@report']);
    Route::resource('payrolls', 'PayrollsController', ['as' => 'admin']);

    //Admin Users
    Route::get('ajax_admin_users/', ['as' => 'admin.ajax_admin_users', 'uses' => 'AdminUsersController@ajax_admin_users']);
    Route::resource('admin_users', 'AdminUsersController', ['as' => 'admin']);

    //Managers
    Route::get('ajax_managers/', ['as' => 'admin.ajax_managers', 'uses' => 'AdminManagersController@ajax_managers']);
    Route::resource('managers', 'AdminManagersController', ['as' => 'admin']);

    //  Job Posted
    Route::get('ajax_jobs/', ['as' => 'admin.ajax_jobs', 'uses' => 'JobsController@ajax_jobs']);
    Route::resource('jobs', 'JobsController', ['as' => 'admin']);

    // Job Applications
    Route::get('job_application/get_download/{resume}', ['as' => 'admin.job_applications.get_download', 'uses' => 'JobApplicationsController@getDownload']);
    Route::post('job_application_change_status/', ['as' => 'admin.job_applications.change_status', 'uses' => 'JobApplicationsController@change_status']);
    Route::get('ajax_jobs_applications/', ['as' => 'admin.ajax_jobs_applications', 'uses' => 'JobApplicationsController@ajax_jobs_applications']);
    Route::resource('job_applications', 'JobApplicationsController', ['as' => 'admin']);

    //Company Setting
    Route::get('company_setting_features', ['as' => 'admin.company_setting.features', 'uses' => 'CompanySettingsController@features']);
    Route::get('company_setting_theme', ['as' => 'admin.company_setting.theme', 'uses' => 'CompanySettingsController@theme']);
    Route::post('company_setting_theme', ['as' => 'admin.company_setting.theme_update', 'uses' => 'CompanySettingsController@updateTheme']);



    Route::get('general-setting', ['as' => 'admin.general_setting.edit', 'uses' => 'CompanySettingsController@generalSetting']);
    Route::put('general-setting', ['as' => 'admin.general_setting.update', 'uses' => 'CompanySettingsController@generalSettingUpdate']);

    Route::get('change_language/', ['as' => 'admin.change_language', 'uses' => 'CompanySettingsController@change_language']);
    Route::get('theme/', ['as' => 'admin.settings.theme', 'uses' => 'CompanySettingsController@theme']);

    Route::resource('company_setting', 'CompanySettingsController', ['as' => 'admin']);

    // Admin Settings
    Route::get('attendance_settings', ['as' => 'admin.attendance_settings.edit', 'uses' => 'CompanySettingsController@attendance']);
    Route::post('attendance_settings/mark_attendance', ['as' => 'admin.attendance_settings.update', 'uses' => 'CompanySettingsController@attendanceUpdateSetting']);

});
// Admin Panel After Login
Route::group(["namespace" => 'Admin', 'middleware' => ['auth.admin', 'auth.screenlock'], 'prefix' => 'admin'], function () {
    //	Dashboard Routing
    Route::get('billing/ajax_billing', ['as' => 'admin.billing.ajax_billing', 'uses' => 'BillingController@ajax_billing']);
    Route::get('billing/ajax_company_name', ['as' => 'admin.billing.ajax_company_name', 'uses' => 'BillingController@ajax_company_name']);
    Route::get('billing/pay/{id}', ['as' => 'admin.billing.pay', 'uses' => 'BillingController@pay']);
    Route::get('billing/pay_razor/{id}', ['as' => 'admin.billing.payRazor', 'uses' => 'BillingController@payRazor']);
    Route::post('billing/pay_2checkout', ['as' => 'admin.billing.pay2checkout', 'uses' => 'BillingController@pay2checkout']);
    Route::get('billing/payment/success', ['as' => 'admin.billing.payment.success', 'uses' => 'BillingController@paymentSuccess']);
    Route::get('billing/payment/cancel', ['as' => 'admin.billing.payment.cancel', 'uses' => 'BillingController@paymentCancel']);
    Route::get('billing/change-plan', ['as' => 'admin.billing.change_plan', 'uses' => 'BillingController@changePlan']);
    Route::get('paypal-recurring', array('as' => 'admin.paypal-recurring','uses' => 'AdminPaypalController@payWithPaypalRecurrring',));
    Route::get('billing/select-package/{packageID}',  'BillingController@selectPackage')->name('admin.billing.select-package');
    Route::post('billing/stripe-payment', ['as' => 'admin.billing.stripe_payment', 'uses' => 'BillingController@stripePayment']);
    Route::post('billing/unsubscribe', ['as' => 'admin.billing.unsubscribe', 'uses' => 'BillingController@cancelSubscription']);

    Route::get('paypal/{packageId}/{type}', array('as' => 'admin.paypal','uses' => 'AdminPaypalController@paymentWithpaypal'));
    Route::resource('billing', 'BillingController', ['as' => 'admin']);


});

// Superadmin Panel Routes
Route::group(["namespace" => 'Admin', 'middleware' => ['auth.superadmin', 'auth.screenlock'], 'prefix' => 'super-admin'], function () {

    Route::get('update-new-version', ['as' => 'admin.updateVersion.index', 'uses' => 'SuperAdminUpdateVersionController@index']);

    //   Profile Setting
    Route::get('profile-settings', ['as' => 'superadmin.profile_settings.edit', 'uses' => 'ProfileSettingsController@edit']);
    Route::post('profile-settings', ['as' => 'superadmin.profile_settings.update', 'uses' => 'ProfileSettingsController@update']);


    Route::get('earning/report/{year}', ['as' => 'admin.earning.report', 'uses' => 'SuperAdminDashboardController@createEarningReport']);
    Route::resource('dashboard', 'SuperAdminDashboardController', ['as' => 'superadmin']);

    //	Contact Request
    Route::post('contact_requests_change_status/', ['as' => 'admin.contact_requests.change_status', 'uses' => 'ContactRequestController@change_status']);
    Route::get('ajax_contact_requests/', ['as' => 'admin.ajax_contact_requests', 'uses' => 'ContactRequestController@ajax_contact_requests']);
    Route::resource('contact_requests', 'ContactRequestController', ['as' => 'admin']);

    //Email Templates
    Route::get('ajax_email_templates/', ['as' => 'admin.ajax_email_templates', 'uses' => 'EmailTemplatesController@ajax_email_templates']);
    Route::resource('email_templates', 'EmailTemplatesController', ['as' => 'admin']);


    // License Types
    Route::put('license_types_country_update/{id}', ['as' => 'admin.license_types_country.update', 'uses' => 'LicenseTypesController@update_country']);
    Route::get('license_types_country_edit/{id}', ['as' => 'admin.license_types_country.edit', 'uses' => 'LicenseTypesController@edit_country']);
    Route::get('ajax_license_types_country/', ['as' => 'admin.ajax_license_types_country', 'uses' => 'LicenseTypesController@ajax_license_types_country']);
    Route::get('ajax_license_types/', ['as' => 'admin.ajax_license_types', 'uses' => 'LicenseTypesController@ajax_license_types']);
    Route::resource('license_types', 'LicenseTypesController', ['as' => 'admin']);

    Route::get('ajax_plans/', ['as' => 'admin.plans', 'uses' => 'PlansController@ajax_plans']);
    Route::resource('plans', 'PlansController', ['as' => 'admin']);

    // FAQ Category
    Route::get('ajax_faq_categories/', ['as' => 'admin.faq_categories', 'uses' => 'FaqCategoryController@ajaxFaqCategories']);
    Route::resource('faq_categories', 'FaqCategoryController', ['as' => 'admin']);

    // FAQ
    Route::get('ajax_faq/', ['as' => 'admin.faqs', 'uses' => 'FaqController@ajaxFaqs']);
    Route::resource('faq', 'FaqController', ['as' => 'admin']);

    // Features
    Route::get('ajax_features/', ['as' => 'admin.features', 'uses' => 'FeaturesController@ajaxFeatures']);
    Route::resource('features', 'FeaturesController', ['as' => 'admin']);

    //Licenses

app/Models/JobApplication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;

class JobApplication extends BaseModel
{

    protected $appends = ['resume_url'];
    protected $hidden = [];
    protected static function boot()
    {
        parent::boot();


        static::addGlobalScope('company', function (Builder $builder) {
            if (admin()) {
                $builder->where('job_applications.company_id', admin()->company_id);
            }
            if (employee()) {
                $builder->where('job_applications.company_id', employee()->company_id);
            }
        });


    }


    // Don't forget to fill this array
    protected $fillable = ['job_id', 'name', 'phone', 'email', 'resume', 'cover_letter', 'submitted_by'];

    protected function job()
    {
        return $this->belongsTo('App\Models\Job', 'job_id', 'id');
    }

    public function employee()
    {

        return $this->belongsTo(Employee::class, 'submitted_by', 'id');
    }

    public function scopeManager($query, $id)
    {
        if (admin()->manager == 1) {
            return $query->join('designation', 'designation.id', '=', 'employees.designation')
                ->join('department', 'designation.department_id', '=', 'department.id')
                ->join('department_manager', 'department_manager.department_id', '=', 'department.id')
                ->where('department_manager.manager_id', '=', $id);
        }
        return $query->join('designation', 'designation.id', '=', 'employees.designation')
            ->join('department', 'designation.department_id', '=', 'department.id');

    }

    public function getResumeUrlAttribute()
    {
        return asset_url('job_applications/' . $this->resume);

    }
}

app/Http/Controllers/Admin/JobApplicationsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Classes\Reply;
use App\Http\Controllers\AdminBaseController;
use App\Http\Requests\Admin\JobApplication\StoreRequest;
use App\Http\Requests\Admin\JobApplication\UpdateRequest;
use App\Http\Requests\Admin\JobApplication\ShowRequest;
use App\Http\Requests\Admin\JobApplication\DeleteRequest;
use App\Models\Employee;
use App\Models\JobApplication;

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\View;

use Yajra\DataTables\Facades\DataTables;

class JobApplicationsController extends AdminBaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->pageTitle = trans('core.jobApplications');
        $this->jobsOpen = 'active';
        $this->jobsApplicationActive = 'active';
    }

    public function index()
    {
        return View::make('admin.job_applications.index', $this->data);
    }

    public function ajax_jobs_applications()
    {
        $result = JobApplication::join('jobs', 'jobs.id', '=', 'job_applications.job_id')
            ->join('employees', 'employees.id', '=', 'job_applications.submitted_by')
            ->manager(admin()->id)
            ->select('job_applications.id', 'jobs.position', 'job_applications.name', 'job_applications.email', 'job_applications.phone', 'job_applications.created_at', 'full_name', 'job_applications.status','job_applications.submitted_by')
            ->get();

        return DataTables::of($result)->editColumn('status', function ($row) {
            $color = ['selected' => 'success', 'rejected' => 'danger', 'pending' => 'warning'];

            $string = "<span  id='status{$row->id}' class='margin-bottom-5 label label-{$color[$row->status]}'>" . trans('core.' . ($row->status)) . "</span>";

            return $string;
        })->addColumn('edit', function ($row) {
            $string = '';
            $display_accept = '';
            $display_reject = '';

            if ($row->status == 'rejected') {
                $display_reject = 'style="display:none"';
            } elseif ($row->status == 'selected') {
                $display_accept = 'style="display:none"';
            }
            $accept = '<a ' . $display_accept . ' id="accept' . $row->id . '"  data-container="body" data-placement="top" data-original-title="Approve" href="javascript:;" onclick="changeStatus(' . $row->id . ',\'selected\');return false;" class="btn green btn-sm tooltips margin-bottom-10"><i class="fa fa-check"></i></a>';
            $reject = '<a ' . $display_reject . ' id="reject' . $row->id . '" data-placement="top" data-original-title="Reject"  href="javascript:;" onclick="changeStatus(' . $row->id . ',\'rejected\');return false;" class="btn red btn-sm tooltips margin-bottom-10"><i class="fa fa-close"></i></a>';

            $string .= '' . $accept . $reject . '';

            $string .= '
						 			<a  class="btn blue-ebonyclay btn-sm margin-bottom-5"  href="javascript:;" onclick="showView(' . $row->id . ');return false;" ><i class="fa fa-eye"></i> ' . trans('core.btnView') . '</a>
	                  	 			<a   href="javascript:;" onclick="del(' . $row->id . ');return false;" class="btn red btn-sm margin-bottom-5">
                        			<i class="fa fa-trash"></i> ' . trans('core.btnDelete') . '</a>';

            return $string;
        })->editColumn('full_name', function ($row) {
            $employee = Employee::find($row->submitted_by);
            return $employee->decryptToCollection()->full_name;
        })
            ->rawColumns(['edit', 'status'])
            ->make();
    }

    public function change_status()
    {
        $job_application = JobApplication::findOrFail(request()->id);
        $job_application->status = request()->status;
        $job_application->save();


        return Reply::success('messages.updateSuccess');
    }

    public function create()
    {
        return View::make('admin.job_applications.create');
    }

    /**
     * @param StoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreRequest $request)
    {
        $data = request()->all();

        JobApplication::create($data);

        return Redirect::route('admin.job_applications.index');
    }


    public function show(ShowRequest $request, $id)
    {

        $this->job_application = JobApplication::findOrFail($id);
        $this->color = ['selected' => 'success', 'rejected' => 'danger', 'pending' => 'warning'];

        return View::make('admin.job_applications.show', $this->data);
    }

    public function getDownload($resume)
    {

        $file = public_path() . "/uploads/" . $this->folder . "/job_applications/" . $resume;

        return Response::download($file);
    }

    public function edit($id)
    {
        $check = JobApplication::find($id);
        if ($check == null) {
            return View::make('admin.errors.noaccess', $this->data);
        }
        $jobapplication = JobApplication::find($id);

        return View::make('admin.job_applications.edit', compact('jobapplication'));
    }

    /**
     * Update the specified JobApplication in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $check = JobApplication::find($id);

        if ($check == null) {
            return View::make('admin.errors.noaccess', $this->data);
        }

        $jobapplication = JobApplication::findOrFail($id);
        $data = request()->all();

        $jobapplication->update($data);

        return Redirect::route('admin.job_applications.index');
    }

    /**
     * Remove the specified jobapplication from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy(DeleteRequest $request,$id)
    {

        JobApplication::destroy($id);
        return Reply::success('messages.jobDeleteMessage');
    }

}

resources/views/admin/job_applications/create.blade.php
/Users/Ajay/htdocs/hrm/dev/local/app/views/jobApplications/create.blade.php

resources/views/admin/job_applications/edit.blade.php
/Users/Ajay/htdocs/hrm/dev/local/app/views/jobApplications/edit.blade.php

resources/views/admin/job_applications/index.blade.php
@extends('admin.adminlayouts.adminlayout')

@section('head')


    <!-- BEGIN PAGE LEVEL STYLES -->
    {!! HTML::style("assets/global/plugins/select2/css/select2.css")!!}
    {!! HTML::style("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css")!!}
    {!! HTML::style("assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css")!!}
    <!-- END PAGE LEVEL STYLES -->

@stop


@section('mainarea')


    <!-- BEGIN PAGE HEADER-->
    <div class="page-head">
        <div class="page-title"><h1>
                @lang("pages.jobApplications.indexTitle")
            </h1></div>
    </div>
    <div class="page-bar">
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a onclick="loadView('{{route('admin.dashboard.index')}}')">{{__('core.dashboard')}}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">@lang("pages.jobApplications.indexTitle")</span>
            </li>

        </ul>

    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">


            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div id="load">

                {{--INLCUDE ERROR MESSAGE BOX--}}

                {{--END ERROR MESSAGE BOX--}}

            </div>
            <div class="portlet light bordered">

                <div class="portlet-body">


                    <table class="table table-striped table-bordered table-hover" id="jobs">
                        <thead>
                        <tr>
                            <th> @lang("core.serialNo")</th>
                            <th> {{trans('core.position')}} </th>

                            <th> {{trans('core.name')}} </th>
                            <th> {{trans('core.email')}} </th>
                            <th> {{trans('core.phone')}} </th>
                            <th> {{trans('core.appliedOn')}} </th>
                            <th> {{trans('core.submittedBy')}} </th>
                            <th> {{trans('core.status')}} </th>
                            <th> {{trans('core.action')}} </th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->

        </div>
    </div>
    <!-- END PAGE CONTENT-->
    @include('admin.common.delete')
    @include('admin.common.show-modal')
@stop



@section('footerjs')


    <!-- BEGIN PAGE LEVEL PLUGINS -->
    {!! HTML::script("assets/global/plugins/select2/js/select2.min.js")!!}
    {!! HTML::script("assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js")!!}
    {!! HTML::script("assets/global/plugins/datatables/datatables.min.js")!!}
    {!! HTML::script("assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")!!}
    {!! HTML::script("assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js")!!}


    <!-- END PAGE LEVEL PLUGINS -->

    <script>

        var table = $('#jobs').dataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ URL::route("admin.ajax_jobs_applications") }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'position', name: 'position'},
                {data: 'name', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'phone', name: 'phone'},
                {data: 'created_at', name: 'created_at'},
                {data: 'full_name', name: 'full_name'},
                {data: 'status', name: 'status'},
                {data: 'edit', name: 'edit'},
            ],
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"] // change per page values here
            ],
            "sPaginationType": "full_numbers",
            "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                App.init();
                var oSettings = this.fnSettings();
                $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                return nRow;

            },
            "language": {},
            "fnInitComplete": function (oSettings, json) {
                App.init();
            }
        });


        function del(id) {

            $('#deleteModal').modal('show');
            $("#deleteModal").find('#info').html('@lang("messages.jobApplicationsDeleteConfirm")');

            $('#deleteModal').find("#delete").off().click(function () {

                var url = "{{ route('admin.job_applications.destroy',':id') }}";
                url = url.replace(':id', id);

                var token = "{{ csrf_token() }}";

                $.easyAjax({
                    type: 'DELETE',
                    url: url,
                    data: {'_token': token},
                    container: "#deleteModal",
                    success: function (response) {
                        if (response.status === "success") {
                            $('#deleteModal').modal('hide');
                            table.fnDraw();
                        }
                    }
                });

            });

        }

        function changeStatus(id, status) {


            $.easyAjax({
                type: 'POST',
                url: "{{route('admin.job_applications.change_status')}}",
                container: '.page-content',
                data: {'status': status, 'id': id},
                success: function (response) {
                    if (response.status === "success") {
                        table.fnDraw();
                    }
                }
            });
        }

        function showView(id) {
            var get_url = "{{ route('admin.job_applications.show',':id') }}";
            get_url = get_url.replace(':id', id);
            $.ajaxModal('#showModal', get_url);
        }

        function addUpdateLeaveType(id) {

            if (typeof id != 'undefined') {
                var url = "{{ route('admin.leavetypes.update',':id') }}";
                url = url.replace(':id', id);
            } else {
                url = "{{route('admin.leavetypes.store')}}";
            }
            $.easyAjax({
                type: 'POST',
                url: url,
                container: '#leave_type_update_form',
                data: $('#leave_type_update_form').serialize(),
                success: function (response) {
                    if (response.status == "success") {
                        $('#showModal').modal('hide');
                        table.fnDraw();
                    }

                }
            });
        }


    </script>
@stop

resources/views/admin/job_applications/show.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">@lang("pages.jobApplications.indexTitle")</h4>
</div>
<div class="modal-body" id="job_info">
    <div class="tabbable-custom ">
        <ul class="nav nav-tabs ">
            <li class="active">
                <a href="#details" data-toggle="tab" aria-expanded="true">
                    {{trans('core.applicantDetails')}} </a>
            </li>
            <li class="">
                <a href="#resume" data-toggle="tab" aria-expanded="false">
                    {{trans('core.resume')}} </a>
            </li>

        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="details">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">

                        <tbody>
                        <tr>
                            <td><strong>{{trans('core.position')}}:</strong></td>
                            <td>{{$job_application->job->position}}</td>

                        </tr>
                        <tr>
                            <td><strong>{{trans('core.name')}}:</strong></td>
                            <td>{{$job_application->name}}</td>

                        </tr>
                        <tr>
                            <td><strong>{{trans('core.email')}}:</strong></td>
                            <td> {{$job_application->email}}</td>
                        </tr>
                        <tr>
                            <td><strong>{{trans('core.phone')}}:</strong></td>
                            <td> {{$job_application->phone}}</td>
                        </tr>
                        <tr>
                            <td><strong>{{trans('core.submittedBy')}}:</strong></td>
                            <td> {{ $job_application->employee->full_name}}</td>
                        </tr>
                        <tr>
                            <td><strong>{{trans('core.appliedOn')}}:</strong></td>
                            <td> {{$job_application->created_at}}</td>
                        </tr>

                        <tr>
                            <td><strong>{{trans('core.status')}}</strong></td>
                            <td>
                                <span class='margin-bottom-10 label label-{{$color[$job_application->status]}}'>{{trans('core.'.$job_application->status)}}</span>
                            </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tab-pane" id="resume">
                <p><strong>{{trans('core.coverLetter')}}:</strong></p>

                <p>
                    {{$job_application->cover_letter}}
                </p>

                <p>
                    @if($job_application->resume!='')
                        <a href="https://docs.google.com/viewer?url={{$job_application->resume_url}}"
                           target="_blank"
                           class="btn green btn-sm">{{trans('core.btnView')}} {{trans('core.resume')}}</a>
                        
                    @else
                        <span class="label label-info">@lang("core.noResumeUploaded")</span>
                    @endif
                </p>

            </div>

        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn default">{{trans('core.btnClose')}}</button>
</div>